name: Lint Code

on:
  push:
    branches:
      - lint
  pull_request:
    branches:
      - lint
    paths:
      - 'firmware/src/**/*.c'
      - 'firmware/src/**/*.cpp'
      - 'firmware/src/**/*.h'
      - 'firmware/src/**/*.hpp'

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install clang-format
        run: sudo apt-get install clang-format

      - name: Run clang-format
        run: |
          clang-format -i $(find firmware/src/ -name '*.c' -or -name '*.cpp' -or -name '*.h' -or -name '*.hpp')
