name: Lint Code

on:
  pull_request:
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.hpp'

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install clang-format
        run: sudo apt-get install clang-format

      - name: Run clang-format
        run: |
          clang-format -i $(find . -name '*.c' -or -name '*.cpp' -or -name '*.h' -or -name '*.hpp')
          git diff --exit-code
